# Generated by Django 4.1.1 on 2023-01-05 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/bonus/')),
                ('answer', models.TextField()),
                ('no_teams_solving', models.IntegerField(default=0)),
                ('no_teams_solved', models.IntegerField(default=0)),
                ('live_time', models.DateTimeField()),
                ('exp_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/questions/')),
                ('answer', models.TextField()),
                ('no_teams_solving', models.IntegerField(default=0)),
                ('no_teams_solved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('team_name', models.CharField(max_length=100)),
                ('leader_first_name', models.CharField(max_length=100)),
                ('leader_roll_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('leader_whatsapp_number', models.CharField(max_length=100)),
                ('team_logo', models.CharField(max_length=100, null=True)),
                ('player2_first_name', models.CharField(blank=True, max_length=100)),
                ('player2_roll_number', models.CharField(blank=True, max_length=100)),
                ('player3_first_name', models.CharField(blank=True, max_length=100)),
                ('player3_roll_number', models.CharField(blank=True, max_length=100)),
                ('player4_first_name', models.CharField(blank=True, max_length=100)),
                ('player4_roll_number', models.CharField(blank=True, max_length=100)),
                ('player5_first_name', models.CharField(blank=True, max_length=100)),
                ('player5_roll_number', models.CharField(blank=True, max_length=100)),
                ('league', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('skips', models.IntegerField(default=1)),
                ('no_bonus_solved', models.IntegerField(default=0)),
                ('no_negative_score', models.IntegerField(default=0)),
                ('curr_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sarcasm.stage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
