# Generated by Django 4.1.4 on 2023-01-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarcasm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='image',
        ),
        migrations.AddField(
            model_name='register',
            name='bonus_type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='register',
            name='curr_bonus_level',
            field=models.IntegerField(default=0),
        ),
    ]
